### PR TITLE
Enforce address alignement with Xen

### PR DESCRIPTION
**Pull request by palainp**
Dear devs,
Xen needs to manipulate io_pages that are aligned and Mirage block drivers are not aware of that. This PR adds the io_pages allocations and copies in and out. This is needed to be able to read (write not tested so far, the only tests I've done are with a unikernel reading a text file at startup from a tar archive copied as its Qubes volume) from a Qubes block disk.
Best.

### CODE REVIEW

**Comment by palainp** [comment]
And while at it (touching read and write), maybe issue #94 can be solved?

**Comment by palainp** [comment]
Maybe it worth to check if the cstructs are page-aligned and re-use `to_iopage`? This introduces two code paths but avoid copies when the device using those blocks is aware of the alignment requirement.

**Comment by reynir** [comment]
We could indeed use `Cstruct.check_alignment` to see if the buffer can be used as-is. The upside is less copying in some cases. The downside is the performance is less predictable, and bugs by use during write of the buffer will not always manifest (which is maybe okay).

**Review by reynir — APPROVED** [review]
I'm in favor of merging this as is as it fixes a real issue. Checking alignment and avoiding a copy can be done in a later PR.

**Comment by palainp** [comment]
Thank you! I'll try to merge and recall the process for cutting a release  this weekend!

**Pull request merged**
